![Piggy bank](piggy_bank.jpg)

Personal loans are a lucrative revenue stream for banks. The typical interest rate of a two-year loan in the United Kingdom is [around 10%](https://www.experian.com/blogs/ask-experian/whats-a-good-interest-rate-for-a-personal-loan/). This might not sound like a lot, but in September 2022 alone UK consumers borrowed [around £1.5 billion](https://www.ukfinance.org.uk/system/files/2022-12/Household%20Finance%20Review%202022%20Q3-%20Final.pdf), which would mean approximately £300 million in interest generated by banks over two years!

You have been asked to work with a bank to clean the data they collected as part of a recent marketing campaign, which aimed to get customers to take out a personal loan. They plan to conduct more marketing campaigns going forward so would like you to ensure it conforms to the specific structure and data types that they specify so that they can then use the cleaned data you provide to set up a PostgreSQL database, which will store this campaign's data and allow data from future campaigns to be easily imported. 

They have supplied you with a csv file called `"bank_marketing.csv"`, which you will need to clean, reformat, and split the data, saving three final csv files. Specifically, the three files should have the names and contents as outlined below:

## `client.csv`

| column | data type | description | cleaning requirements |
|--------|-----------|-------------|-----------------------|
| `client_id` | `integer` | Client ID | N/A |
| `age` | `integer` | Client's age in years | N/A |
| `job` | `object` | Client's type of job | Change `"."` to `"_"` |
| `marital` | `object` | Client's marital status | N/A |
| `education` | `object` | Client's level of education | Change `"."` to `"_"` and `"unknown"` to `np.NaN` |
| `credit_default` | `bool` | Whether the client's credit is in default | Convert to `boolean` data type:<br> `1` if `"yes"`, otherwise `0` |
| `mortgage` | `bool` | Whether the client has an existing mortgage (housing loan) | Convert to boolean data type:<br> `1` if `"yes"`, otherwise `0` |

<br>

## `campaign.csv`

| column | data type | description | cleaning requirements |
|--------|-----------|-------------|-----------------------|
| `client_id` | `integer` | Client ID | N/A |
| `number_contacts` | `integer` | Number of contact attempts to the client in the current campaign | N/A |
| `contact_duration` | `integer` | Last contact duration in seconds | N/A |
| `previous_campaign_contacts` | `integer` | Number of contact attempts to the client in the previous campaign | N/A |
| `previous_outcome` | `bool` | Outcome of the previous campaign | Convert to boolean data type:<br> `1` if `"success"`, otherwise `0`. |
| `campaign_outcome` | `bool` | Outcome of the current campaign | Convert to boolean data type:<br> `1` if `"yes"`, otherwise `0`. |
| `last_contact_date` | `datetime` | Last date the client was contacted | Create from a combination of `day`, `month`, and a newly created `year` column (which should have a value of `2022`); <br> **Format =** `"YYYY-MM-DD"` |

<br>

## `economics.csv`

| column | data type | description | cleaning requirements |
|--------|-----------|-------------|-----------------------|
| `client_id` | `integer` | Client ID | N/A |
| `cons_price_idx` | `float` | Consumer price index (monthly indicator) | N/A |
| `euribor_three_months` | `float` | Euro Interbank Offered Rate (euribor) three-month rate (daily indicator) | N/A |

In [1]:
import pandas as pd
import numpy as np
# Start coding here...

In [129]:
df = pd.read_csv("bank_marketing.csv")

for col in ["credit_default", "mortgage", "previous_outcome", "campaign_outcome"]:
    print(col)
    print("--------------")
    print(df[col].value_counts())

credit_default
--------------
credit_default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64
mortgage
--------------
mortgage
yes        21576
no         18622
unknown      990
Name: count, dtype: int64
previous_outcome
--------------
previous_outcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64
campaign_outcome
--------------
campaign_outcome
no     36548
yes     4640
Name: count, dtype: int64

In [130]:
df.head()

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome
0,0,56,housemaid,married,basic.4y,no,no,may,13,261,1,0,nonexistent,93.994,4.857,no
1,1,57,services,married,high.school,unknown,no,may,19,149,1,0,nonexistent,93.994,4.857,no
2,2,37,services,married,high.school,no,yes,may,23,226,1,0,nonexistent,93.994,4.857,no
3,3,40,admin.,married,basic.6y,no,no,may,27,151,1,0,nonexistent,93.994,4.857,no
4,4,56,services,married,high.school,no,no,may,3,307,1,0,nonexistent,93.994,4.857,no

In [131]:
print(df['mortgage'].unique())
print(df['credit_default'].unique())

['no' 'yes' 'unknown']
['no' 'unknown' 'yes']

In [132]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   client_id                   41188 non-null  int64
 1   age                         41188 non-null  int64
 2   job                         41188 non-null  object
 3   marital                     41188 non-null  object
 4   education                   41188 non-null  object
 5   credit_default              41188 non-null  object
 6   mortgage                    41188 non-null  object
 7   month                       41188 non-null  object
 8   day                         41188 non-null  int64
 9   contact_duration            41188 non-null  int64
 10  number_contacts             41188 non-null  int64
 11  previous_campaign_contacts  41188 non-null  int64
 12  previous_outcome            41188 non-null  object
 13  cons_price_idx              41188 non-null  float64
 14  euribor_three_months        41188 non-null  float64
 15  campaign_outcome            41188 non-null  object
dtypes: float64(2), int64(6), object(8)
memory usage: 5.0+ MB

In [137]:
df['job'] = df['job'].replace('.','_')
df['education'] = df['education'].replace({'.': '_', 'unknown': np.NaN}, regex=True)

In [124]:
df['credit_default'].isna().sum()

0

In [127]:
df['credit_default'] = df['credit_default'].map({'yes': 1, 'no': 0,'unknown':0}).astype(int).astype(bool)
df['mortgage'] = df['mortgage'].map({'yes': 1, 'no': 0,'unknown':0}).astype(int).astype(bool)

In [128]:
df['credit_default'].unique()

array([False,  True])

In [126]:
df['previous_outcome'].unique()

array(['nonexistent', 'failure', 'success'], dtype=object)

In [106]:
df['previous_outcome'] = df['previous_outcome'].map({'success': 1, 'failure': 0,'nonexistent':0}).astype(int).astype(bool)

In [107]:
df['campaign_outcome'].unique()

array(['no', 'yes'], dtype=object)

In [108]:
df['campaign_outcome']= df['campaign_outcome'].map({'yes': 1, 'no': 0}).astype(int).astype(bool)

In [109]:
df['month'].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'mar', 'apr',
       'sep'], dtype=object)

In [110]:
df['month'] = df['month'].str.capitalize()
df['last_contact_date'] = pd.to_datetime(df['month'] + " " + df['day'].astype(str) + " " + str(2022), format='%b %d %Y')
df['last_contact_date'] = df['last_contact_date'].dt.strftime('%Y-%m-%d')

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   client_id                   41188 non-null  int64
 1   age                         41188 non-null  int64
 2   job                         41188 non-null  object
 3   marital                     41188 non-null  object
 4   education                   39457 non-null  object
 5   credit_default              41188 non-null  int32
 6   mortgage                    41188 non-null  int32
 7   month                       41188 non-null  object
 8   day                         41188 non-null  int64
 9   contact_duration            41188 non-null  int64
 10  number_contacts             41188 non-null  int64
 11  previous_campaign_contacts  41188 non-null  int64
 12  previous_outcome            41188 non-null  int32
 13  cons_price_idx              41188 non-null  float64
 14  euribor_three_months        41188 non-null  float64
 15  campaign_outcome            41188 non-null  int32
 16  last_contact_date           41188 non-null  object
dtypes: float64(2), int32(4), int64(6), object(5)
memory usage: 4.7+ MB

In [112]:
df.head()

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,last_contact_date
0,0,56,housemaid,married,basic.4y,0,0,May,13,261,1,0,0,93.994,4.857,0,2022-05-13
1,1,57,services,married,high.school,0,0,May,19,149,1,0,0,93.994,4.857,0,2022-05-19
2,2,37,services,married,high.school,0,1,May,23,226,1,0,0,93.994,4.857,0,2022-05-23
3,3,40,admin.,married,basic.6y,0,0,May,27,151,1,0,0,93.994,4.857,0,2022-05-27
4,4,56,services,married,high.school,0,0,May,3,307,1,0,0,93.994,4.857,0,2022-05-03

In [113]:
client_df = df[['client_id','age','job','marital','education','credit_default','mortgage']]
client_df.to_csv("client_data.csv",index=False)

In [114]:
campaign_df = df[['client_id','number_contacts','contact_duration','previous_campaign_contacts','previous_outcome','campaign_outcome','last_contact_date']]
campaign_df.to_csv("campaign_data.csv",index=False)

In [115]:
economic_df = df[['client_id','cons_price_idx','euribor_three_months']]
economic_df.to_csv("economic_data.csv",index=False)